---

- name: Ansible Conditionals Bool
  hosts: all
  vars:
    backup: true
    snapshot: false
  tasks:
    - name: Run the task if 'backup' is true
      ansible.builtin.debug:
        msg: "Congratulations"
      when: backup | bool
    
    - name: Run the task if 'backup' is false
      ansible.builtin.debug:
        msg: "Critical. Make backup."
      when: not backup

...
