---

- name: Update Rocky Linux Servers - Starting Deploy
  hosts: rocky01
  tasks:
   - name: DNF | Update System
     ansible.builtin.dnf: 
       name: "*"
       state: latest
       update_cache: yes

- name: Update Ubuntu Linux Servers - Starting Deploy
  hosts: ubuntu01
  tasks:
   - name: Ubuntu Like | Update System
     ansible.builtin.apt: name="*" state=latest

...
