---

- name: Testando variaveis
  hosts: rocky01
  vars:
    message: "nova mensagem"
    packages:
      - htop
      - vim
  tasks:
    - name: DEBUG | {{ message }}
      ansible.builtin.debug:
        msg: "{{ message }}"

    - name: DNF | Add EPEL repository
      ansible.builtin.dnf:
        name: epel-release
        state: present

    - name: DNF | Update all packages
      ansible.builtin.dnf:
        name: "*"
        state: latest

    - name: DNF | Install packages
      ansible.builtin.dnf:
        name: "{{ packages }}"
        state: latest

...