---

- name: Testando variaveis
  hosts: rocky01
  vars_files: varsfiles.yml
  tasks:
    - name: DNF | Install packages
      ansible.builtin.dnf:
        name: "{{ packages }}"
        state: latest

...
