---

- name: Ansible Register
  hosts: all
  tasks:
    - name: SISOP | Find files
      find:
        path: /
        patterns: '*.*'
      register: output

    - name: SISOP | Show files
      debug: 
        msg: "{{ output }}"

...
